### ISSUE TITLE
Can't edit existing categories from admin panel

### ISSUE THREAD

**Issue by Fweeb** [armadillica/dillo#10]
Currently, it's not possible to edit or delete existing categories from the admin panel. You currently have to work around this by editing the database directly.

The source of the problem appears to be a missing table in the database... specifically `categories_roles`. The following is a report of the error from the apache logs:

    [Sat Mar 26 14:25:23.549115 2016] [:error] [pid 4230:tid 139690892015360] [remote <IP_ADDRESS>:38479] ProgrammingError: (_mysql_exceptions.ProgrammingError) (1146, "Table 'rightclickselect.categories_roles' doesn't exist") [SQL: u'SELECT role.id AS role_id, role.name AS role_name, role.description AS role_description \\nFROM role, categories_roles \\nWHERE %s = categories_roles.category_id AND role.id = categories_roles.role_id'] [parameters: (18L,)]

I could add this table manualy (and will probably have to), but I'd need to know what its schema looks like.

**Comment by fsiddi** [comment]
Hi,

this issue is fixed by migrating the database to the latest version (we introduced access management via roles for categories). We are going to close this. If you have any question please reopen the issue and let us know!
