### ISSUE TITLE
Markdown parsing broken

### ISSUE THREAD

**Issue by Fweeb** [armadillica/dillo#101]
As of this report, it seems that Markdown parsing is broken. If you look at recently posted ideas on [Right-Click Select](https://blender.community/c/rightclickselect/), none of them seem to have intended paragraph breaks or other markup.

**Comment by venomgfx** [comment]
Confirmed. We were just talking about this with @fsiddi, last night a new update brought some unexpected changes. Working on a fix right now. Thanks for the report and apologies for the trouble.
