### ISSUE TITLE
Edit newline parsing

### ISSUE THREAD

**Issue by IFinnimore** [armadillica/dillo#102]
Noted on the RightClick site (This is a copy of a comment on topic "Outliner: Boundary cross scrolling when dragging object", by me)

There seems to be a site markdown parsing edit text bug[

]The NEWLINE is ignored if adjacent to a character[ ] or a single space [ ] NEWLINE is only respected if prefixed by 2 spaces [
] Or there are 2 in a row[

]In this comment all enter presses are just before the close square brace, for ref.
===
Editing of text in both comments and posts are affected.

**Comment by venomgfx** [comment]
Fixed in Dillo 4.0 using Markdown (commonmark)
