### ISSUE TITLE
dillo docker 

### ISSUE THREAD

**Issue by trew100** [armadillica/dillo#104]
Hi guys

there is planning for official dillo docker?

for now the docker compose file in the repo doesn't works well

**Comment by fsiddi** [comment]
Hi, there is no plan to make a generic dillo docker image for the moment, since the configuration/setup is still quite involved. Could you let us know the the error you get when using the docker-compose?

**Comment by trew100** [comment]
> 
> 
> Hi, there is no plan to make a generic dillo docker image for the moment, since the configuration/setup is still quite involved. Could you let us know the the error you get when using the docker-compose?

hi 
I run compose from dillo/docker/docker-compose
the build of the compose finished without error but the site doesn't display
after investigation I see that `celery_worker` container return this error 

```
  File "/data/git/dillo/runserver.py", line 8, in <module>
    app = PillarServer('.')
  File "/data/git/pillar/pillar/__init__.py", line 99, in __init__
    self._load_flask_config()
  File "/data/git/pillar/pillar/__init__.py", line 169, in _load_flask_config
    self.config.from_pyfile(from_envvar, silent=False)
  File "/opt/python/lib/python3.6/site-packages/flask/config.py", line 129, in from_pyfile
    with open(filename, mode='rb') as config_file:
FileNotFoundError: [Errno 2] Unable to load configuration file (No such file or directory): '/data/config/config_secrets.py'
```

I will happy to get involved to get docker work
but first I need to run the app successfully

**Comment by venomgfx** [comment]
Dillo 4.0 doesn't rely on Pillar anymore so I'm closing this.
