### ISSUE TITLE
Better integration when posting blender.community links on the web

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#105]
It's pretty common on the web that when you post a link, a quick preview is made out of that link.

E.G. in discord, if I post this repository's link, Discord generates a little card with the page title, repo's short description, user icon...

![image](https://user-images.githubusercontent.com/16049822/57065588-3632c000-6cca-11e9-9bdb-bcb44dd5e30a.png)

Same if I post the wikipedia link of Blender:

![image](https://user-images.githubusercontent.com/16049822/57065628-55315200-6cca-11e9-8faf-60b6ab733ed1.png)

It allows the reader to have a brief preview of what the link is about. And for people actually writing the articles, it allows them an efficient share on social medias.

But when I post a blender.community link, all I get is the community's name:

![image](https://user-images.githubusercontent.com/16049822/57065679-78f49800-6cca-11e9-883a-b80b587ac56c.png)

Even worse on Twitter:

![image](https://user-images.githubusercontent.com/16049822/57088745-3ac79a80-6d03-11e9-9d23-7f3d2b8db714.png)

The issue here is that it doesn't reflect the link's content. If I post several links from RCS, they will all display the same infos even though they are different:

![image](https://user-images.githubusercontent.com/16049822/57065916-25cf1500-6ccb-11e9-93cd-589180249fae.png)

It could be way more interesting to also have the article's name and its icon.

**Comment by venomgfx** [comment]
This improvement is now deployed and live in production.

**Comment by L0Lock** [comment]
This is WAY better! 😊 I mean, look at this thing:
![demo pic](https://i.imgur.com/UaDDsBq.png)

Though there is still a little improvement possible: as you can see in this picture, the markdown tags get displayed as is instead of being parsed into text formatting.  
So it would be nice if the markdown included in this preview text would be taken into account properly. If it's not possible, maybe remove it completely as it makes the text less readable?

Also, I don't know the standard in English, but:  
In French, when we shorten a quote, we indicate it with ` (...)` instead of `...` (with space before the `(`). Because `...` alone could be the original text, while ` (...)` makes it clear that it is a shortened quote. Would that be interesting for dillo?
