### ISSUE TITLE
Conflict with the "current comunity" hover

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#107]
See that GIF:

![demo gif](https://i.imgur.com/W8B6SAk.gif)

I'm only trying to click on an element of the list. But as soon as I'm getting near the "current" community icon, this icon expands and make me click on the community shortcut instead of the thread.

It's even worse when writing a post:

![demo gif 2](https://i.imgur.com/obzrEom.gif)

Sometimes I just can't click the text I want, or my browser try to load another page. If there was no warning popup in my browser when I try to leave a form being filled, I would have lost my whole post several times.

**Comment by venomgfx** [comment]
This fix is now deployed and live in production.
