### ISSUE TITLE
Improve notifications text

### ISSUE THREAD

**Issue by venomgfx** [armadillica/dillo#108]
https://blender.community/c/rightclickselect/2kdbbc/

![image](https://user-images.githubusercontent.com/2890874/58252316-1c831680-7d66-11e9-92b3-a23f47b65d3e.png)

**Comment by L0Lock** [comment]
I think it would be nice if there also was a button to clear all notifications of a single thread. It could be done automatically as you read through, but I think it's more flexible to let the user choose himself.

**Comment by L0Lock** [comment]
btw: #87

**Comment by venomgfx** [comment]
We have just deployed a fix for this in production, for notifications. Next up on the list is making the same for profile's history, which we will work on as soon as possible.

Leaving this issue open until we address that.
