### ISSUE TITLE
Make images on comments expandable.

### ISSUE THREAD

**Issue by venomgfx** [armadillica/dillo#109]

**Comment by xan2622** [comment]
Do you mean that if images in comments _(that currently fill the comment div width)_ are clicked, they would be displayed in another tab, displaying the original image (full) dimensions?
If this is what you meant, I like the idea.

**Comment by venomgfx** [comment]
Exactly, that's still to be implemented.

**Comment by venomgfx** [comment]
Implemented nearly 2 years later in 1e58db8dcfbbf76069296ea7e8c334c3bbf36404
