### ISSUE TITLE
Question: Post Properties

### ISSUE THREAD

**Issue by Fweeb** [armadillica/dillo#11]
I noticed a table in the database called post_properties. Currently it isn't really used for anything in the code and a running site doesn't have any fields in this table populated. In the code, there's a comment referencing Twitter IDs, Google IDs, or Gallery images.

What's the intended purpose of this table? Could it be used to add administrative tags to posts? In my case, I would use it for marking posts as Incomplete, Duplicate, Committed, etc. Is that the right use for this table, or should I be creating a separate table for such a feature?

**Comment by fsiddi** [comment]
That table was introduced with the intention of solving the "how do I add custom props to my post" problem in a way similar to how WP does it. After careful consideration we do not think that's the way to go and we plan to solve the problem with *custom modules*.

Custom modules allow to define your own entry point, data structures, validation, templates and so on. We plan to develop this in the near future, right after the tagging of the current release. If the plan works out, post_properties will be removed. So if possible I would avoid using it.

Closing for now, feel free to reopen for further discussion.
