### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#112]
Coming from [#111](https://github.com/armadillica/dillo/issues/111#issuecomment-502383124),
It may be nice for newcomers to have an About page to understand what this place is because to be honest, even to me it's still not cristal clear on the "per-language" communities. I heard some people call them forums and seen some others use them as if they were Blender StackExchange clones where they can speak their language.
I assume there's no strict rule but would you say it's supposed to be just news and art-sharing or is it truly open to other uses and which ones?

**Comment by ChameleonScales** [comment]
Nice, thanks!
Little hidden though I would say.
Maybe there could be a link to it in the home page https://blender.community/c/ ?

**Comment by venomgfx** [comment]
> Nice, thanks!
> Little hidden though I would say.
> Maybe there could be a link to it in the home page https://blender.community/c/ ?

Good point! I have added it. Thanks for the idea!

**Comment by ChameleonScales** [comment]
Thanks
The "Found a bug?" seems to lead some people to think it's a bug report link for Blender itself : #117
Perhaps it should say "Found a bug on this website?" to clarify.

**Comment by fsiddi** [comment]
Thank you for the hint. Perhaps @venomgfx can tweak this?

**Comment by venomgfx** [comment]
> Thank you for the hint. Perhaps @venomgfx can tweak this?

Done.

**Comment by ChameleonScales** [comment]
Sorry, I didn't precise I was talking about the home page rather than the about page.

**Comment by venomgfx** [comment]
Oh that's even simpler. Fixed. Thanks!

**Comment by ChameleonScales** [comment]
Another confusion: #119 
The about page still just says "Found a bug". Maybe there too we should give more precision.

**Comment by venomgfx** [comment]
Yes, [a fix for this has been committed already](https://github.com/armadillica/dillo/commit/db43bc4c6fb764da0aa613dbdd28e9f055bd14e2), we just didn't have time to deploy it in production yet. Once 2.80 is released things will hopefully go back to normal.
