### ISSUE TITLE
Big search bar on RCS's home page

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#113]
Duplicates are still a problem on RCS and I think one reason is that the search bar is not obvious enough.
I would suggest adding a more "in-your-face" search bar on the home page so no one can miss it.
Mockup:

![](https://i.imgur.com/vcXvIVH.png)

Note that I removed the search bar on the top to avoid any confusion but this would only happen on the home page.
I also removed the "What's going on" part as I'm not sure it's very useful but if you prefer to leave it that's ok for me.

**Comment by xan2622** [comment]
I second this idea. 

The RightClickSelect [front page](https://blender.community/c/rightclickselect/) has enough free space to fit a big Search Field.

About the search bar at the top, I agree with @ChameleonScales, I would still keep it while browsing suggestions (but not on the home page). But think that it would deserve to be enlarged a little bit.

**Comment by venomgfx** [comment]
Search is now in the header.

**Comment by ChameleonScales** [comment]
Wasn't it always? The proposal was to put it in the middle of the home page.
btw congratulations on the new version, I'm very curious to see how it turns out.

**Comment by venomgfx** [comment]
Yes it's always been in the header, I think moving it somewhere else just for 1 community can be confusing.

Search should always be in the same, familiar place. The duplicates problem should be addressed differently (we currently show a warning to first-time-posters, and plan to implement a better workflow to mark/find duplicates).
