### ISSUE TITLE
Issues with moving Texture as Stencil to drawing texture above 3d model

### ISSUE THREAD

**Issue by PStudio3D** [armadillica/dillo#117]
Hotkeys didn't work properly for moving image in the 2d and 3d views.

**Comment by PStudio3D** [comment]
sorry. download new version and everything works correctly :)

**Comment by ChameleonScales** [comment]
@PStudio3D it seems you confused this place for the Blender bug tracker. It's actually the dillo (used to make the blender.community website) bug tracker.
To report bugs on Blender itself, go to https://developer.blender.org/maniphest/task/edit/form/1/
