### ISSUE TITLE
upload error GraphicAll

### ISSUE THREAD

**Issue by King-Wally** [armadillica/dillo#120]
I get a error saying: "uploaded bytes exceed file size" every time I try to upload a new build on GraphicAll. The zip file I try to upload is 112 Mb, I never had any issue uploading files of this size before.

**Comment by venomgfx** [comment]
We ran out of space on the server, we are working on a solution. Sorry for the trouble.

**Comment by JohJakob** [comment]
I just encountered the same issue again.

**Comment by venomgfx** [comment]
We ran out of space again. I've made some room, hopefully it works now.

**Comment by JohJakob** [comment]
It’s working again. Thanks, Pablo!

**Comment by paulhart2** [comment]
Once again having this same problem, file size is not different than prior builds, tried for three(3) days, no success???

**Comment by fsiddi** [comment]
I added yet more space. This issue should not happen again. Please retry and feel free to reopen the issue if you still can't upload.
