### ISSUE TITLE
Bug: I can't see all of my own suggestion on my profile page.

### ISSUE THREAD

**Issue by IIIFGIII** [armadillica/dillo#121]
Here is one of my old suggestion posted 13 February 2018
![GitHub Logo](https://i.imgur.com/nNvph2v.png)
But last one I can see in my profile is Outliner Revork 01 November 2018
![GitHub Logo](https://i.imgur.com/cPbDXA8.png)

**Comment by fsiddi** [comment]
Thanks for the report. Will be solved by #97.
