### ISSUE TITLE
Problem logging into sites with my Blender ID

### ISSUE THREAD

**Issue by AndySellers** [armadillica/dillo#123]
I'm having a problem logging into sites that use the Blender ID. When I try, I get a message:

Secure Connection Failed
An error occurred during a connection to id.blender.org. PR_END_OF_FILE_ERROR 
The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.

This problem occurs when I try to log into any site with my Blender ID. I use Firefox most of the time, but I also get an error with other browsers.

**Comment by fsiddi** [comment]
Hi, can you please confirm which version of Firefox you are using and on which OS? Does the issue still happen?

**Comment by AndySellers** [comment]
I'm using Windows 10 version 1803, and Firefox version 70.0.1.
Thanks!

**Comment by venomgfx** [comment]
Being a Blender ID issue and not entirely related to Dillo, shouldn't this be reported on https://developer.blender.org/diffusion/BID/ ?

**Comment by fsiddi** [comment]
It's still not clear, because this could be a Dillo specific issue. One thin @AndySellers could try is to confirm if logging in to a different website (for example cloud.blender.org) causes the same problem.

**Comment by AndySellers** [comment]
As far as I can tell, this happens with every site that uses the Blender ID as a login.
@venomgfx is there a specific place to report it on https://developer.blender.org/diffusion/BID/ ? I didn't see an obvious place.

**Comment by fsiddi** [comment]
Did you try what is being suggested here? https://support.mozilla.org/en-US/questions/1267074 
From what I understand, it seems to be a Firefox specific issue.

**Comment by venomgfx** [comment]
Blender ID, Dillo, even browsers have been through so long since 2019 that I will close this. Feel free to open a new issue if it happens again.
