### ISSUE TITLE
RCS - User's page proposals display limit

### ISSUE THREAD

**Issue by Ryxx** [armadillica/dillo#124]
I made too many proposals on RCS, and my user page doesn’t display all of them anymore. They are hidden and there is no way to get at them without doing a search. Would it be possible to make a “Load more” button?

**Comment by venomgfx** [comment]
Hi, we are aware of this bug working on a solution.  Thanks for the report!

**Comment by xan2622** [comment]
I second this request. 

I hope that, someday, a user would have the ability to browse all his/her topics, replies & votes.
Being able to browse the full user history would be indeed useful.

**Comment by venomgfx** [comment]
Fixed in Dillo 4.0 by having the "See All" link
![image](https://user-images.githubusercontent.com/2890874/122293069-f0133780-cef6-11eb-8be3-f4a64699196e.png)
