### ISSUE TITLE
Add the Suggestion Title to the Profile history

### ISSUE THREAD

**Issue by xan2622** [armadillica/dillo#126]
In the user profile page, instead of just displaying:
- _1 week ago_ **Richard** commented

It would be nice to see the _title of the suggestion_ too: 

- _1 week_ ago **Richard** commented on "Snap to Face Center"
 ("Snap to Face Center" being also clickable).

It would make the Profile (at least, this History / Activity area) clearer, faster to understand what a user did (to know in which suggestion a comment has been posted and which suggestion has been upvoted/downvoted).

**Comment by venomgfx** [comment]
This will be implemented in the upcoming version 4.0, under development coming later this year.

Thanks!

**Comment by venomgfx** [comment]
![image](https://user-images.githubusercontent.com/2890874/118899662-86136c80-b90f-11eb-81ef-94cb61997d3a.png)

Already implemented in v4.
