### ISSUE TITLE
Add an option to reset votes (to remove votes)

### ISSUE THREAD

**Issue by xan2622** [armadillica/dillo#127]
AFAIK, if a user upvoted an idea, the only other available choice is to downvote. 

Downvoting a suggestion (that was previously upvoted) could be enough if the user completely changed his/her mind, but not really if the user just wants to remove his/her vote.

It might be interesting to let users reset their votes (as if the user hasn't voted at all).

**Comment by venomgfx** [comment]
You can undo a vote by clicking on the arrow again (up for undo upvote, down for undo downvote), is this what you meant?

**Comment by xan2622** [comment]
Yes, exactly. Sorry for creating this Github issue. 
I didn't know it is already possible.
