### ISSUE TITLE
Allow to link to comments

### ISSUE THREAD

**Issue by xan2622** [armadillica/dillo#128]
AFAIK, it's not currently possible to directly link to a comment (to get the direct url of comments).

It would be convenient if **dates of comments** could be clickable links.

![Annotation 2020-04-27 090435](https://user-images.githubusercontent.com/1732773/80515682-9e21f200-8982-11ea-8ca0-3b203154f5ac.png)

**Comment by venomgfx** [comment]
This is already implemented in the upcoming version 4.0, under development coming later this year.

Thanks for the feedback!
