### ISSUE TITLE
Profile and Links (in user profile) unthemed in Dark mode.

### ISSUE THREAD

**Issue by xan2622** [armadillica/dillo#129]
When the Dark theme is enabled, there are some elements that still use the Light theme: https://blender.community/settings/profile

![Annotation 2020-04-29 220127](https://user-images.githubusercontent.com/1732773/80641447-2d9fd180-8a65-11ea-9764-164359e6eeb7.png)

**Comment by venomgfx** [comment]
Fixed in 4.0
