### ISSUE TITLE
[Request] keep 404 page inside Dillo's UI

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#131]
My situation is, I clicked a notification in RCS, and because the post has been deleted, I was redirected on the 404 page.

The issue is, the 404 page is a blank page, no way to easily get back to the actual Dillo from the page itself, you have to manually load the previous page first to be able to browse again, which is an avoidable extra step and not user friendly.

I propose to simply change the 404 page so it remains inside Blender Community, or better, also stay in the current community the user was before clicking a link from the site.

Mockup:

![image](https://user-images.githubusercontent.com/16049822/86001704-8eb93680-ba0f-11ea-9d1d-9342e6d9bc65.png)

**Comment by fsiddi** [comment]
Thanks for the feedback! The upcoming version of Dillo will handle this more reliably. While we have no set date for an upgrade, but we will consider the issue solved when that happens.

**Comment by venomgfx** [comment]
Fixed in Dillo 4.0
