### ISSUE TITLE
Spammer report.

### ISSUE THREAD

**Issue by christianclavet** [armadillica/dillo#132]
Got this user that is creating spam content into the community. He seem to have multiple account and put "up" sign on his posts.
Here is the link to the user:
https://blender.community/u/ieltsptebuy2020

All of theses posts are spam.

Will there be a way to declare spammer directly in the web site? I did not find anyway to report them except here...
Thank.

**Comment by venomgfx** [comment]
The current site has very limited moderation tools, when we made it the site was so small we didn't think there would be need even. So it's kind of hard to go and ban users or easily delete them.

The new version of Dillo that we're working on already has a report system and makes it easier for deletion and ban of users, comments and posts. 

Thanks for the report Christian!

**Comment by christianclavet** [comment]
Hi, 

Update: Spammer striked again!

He created|used another account and continue to spam the Blender french community:
https://blender.community/u/maamahamida

Got 6 spam post in a row. (Bot?)

**Comment by fsiddi** [comment]
Posts have been removed.
