### ISSUE TITLE
When there are too many badges

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#135]
I just stumbled upon [this comment](https://blender.community/c/rightclickselect/fwgbbc/#5f4ba2449c122166e371e326):

![image](https://user-images.githubusercontent.com/16049822/91660566-06224980-ead7-11ea-8737-2430070f8313.png)

Just a line of comment, yet it takes the place of a big comment. I first thought the page wasn't fully loaded. But no, it's just the badges taking a lot of place.

I'm no wed designer, but maybe there's a better way to manage this without over-spacing?

**Comment by venomgfx** [comment]
Fixed in Dillo 4
