### ISSUE TITLE
Submit Proposal and other similar "create" buttons sends to "404 Not Found"

### ISSUE THREAD

**Issue by minisauruslepro** [armadillica/dillo#138]
https://blender.community/c/
Trying to suggest stuff send me to the 404 error message.

**Comment by venomgfx** [comment]
Can't seem to reproduce. Can you give more info? Are you logged in? Which community (RightClickSelect, BlenderToday, etc)

**Comment by venomgfx** [comment]
Closing as invalid. Please report if it comes up again.
