### ISSUE TITLE
My account is blocked at #blendertoday #Pablo Vazquez

### ISSUE THREAD

**Issue by ssersoz** [armadillica/dillo#140]
Hi,
I am the developer of "SketchN'Carve" add-on for Blender and a Developer Fund Contributor. My user name is ssersoz. Today I found out my latest post was removed and I was blocked from posting on the Blender.Today site. I was also hit by -10 Karma points. I don't post on the site too frequently, and most of my posts are tutorials on how to use the add-on.
https://blender.community/c/today/lygbbc/

At first I thought I was blocked for promoting a commercial product, but there were other posts promoting their products or the "Black Friday Sales". There were multiple post even as I write this. Some of them posting on the same days as I have (users: "blendernow3d", threcius, etc) promoting their products and yet their posts are still up and karma points unaffected.

I don't know why my account was singled out. I will appreciate it if you could review and hopefully restore my account, as I am sure there must be a mistake.
Thank you for all your tireless efforts in developing my favorite software, and the great "Blender Today" show which I follow religiously!

Sincerely,
ssersoz

**Comment by fsiddi** [comment]
Reached out via mail to solve the issue.
