### ISSUE TITLE
Dillo on mobile: error messages take all the screen

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#142]
I've been using Dillo on mobile phone (some Android 6.stuff), and I have been quite annoyed with the error messages filling up my screen. In fact, even one error message is enough to cover up what you're currently writing.

I tried to record this:

https://user-images.githubusercontent.com/16049822/103491315-16e72100-4e23-11eb-8a37-053ca586f9a1.mp4

Thanks for your attention.

**Comment by venomgfx** [comment]
Could you mention or share a screenshot at least which errors are filling up the page? I don't get any here (also Android)

**Comment by L0Lock** [comment]
Oops! I managed to upload the wrong example. That's corrected, sorry for the time waste.

**Comment by venomgfx** [comment]
This has been fixed in the latest version.
