### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by grpnpraveen** [armadillica/dillo#146]
I have posted two already by from past two days I am facing a problem while wanted to write a post that it saying '404 not found pls report'.
@grpnpraveen Blender.Community

**Comment by BluePrintRandom** [comment]
same !

**Comment by BluePrintRandom** [comment]
https://blender.community/c/rightclickselect/post/text
when I click this I get
![image](https://user-images.githubusercontent.com/7190873/109344733-fe442780-7823-11eb-877a-c891b11bc356.png)

**Comment by grpnpraveen** [comment]
Maybe it's about Karma value in our profile

**Comment by venomgfx** [comment]
> Maybe it's about Karma value in our profile

Yes. As a temporary measure to deal with the overwhelming spam in Blender Community, users with negative karma are not allowed to post.

@grpnpraveen you should be able to post now.

@BluePrintRandom what is your username in Blender Community?

**Comment by grpnpraveen** [comment]
sry for late rply: it's 
![image](https://user-images.githubusercontent.com/10905467/109953805-8768cc00-7d06-11eb-8b62-04bade910e67.png)

**Comment by venomgfx** [comment]
@grpnpraveen you have 5 karma now, you still can't post?

**Comment by grpnpraveen** [comment]
Now I am able to.

**Comment by nurb2kea** [comment]
Having the same problem now. Just new to Blender Today and could post 4 posts, and now I got Karma -5.
I thought someone rated me so bad, but that isn't possible.

So what's the deal with the block of  ability to post and the Karma thing.

Thanks in advance

Nurb2Kea

@Nurb2Kea

**Comment by grpnpraveen** [comment]
@nurb2kea I think there is nothing we can do. Just wait till your karma value becomes positive in your profile.

**Comment by venomgfx** [comment]
@nurb2kea I've increased your karma a little, you should be able to post now. 

We are working on the new system and it should be ready to test in less than a month.

**Comment by nurb2kea** [comment]
Thank you very much Pablo ! :-))
I was worried I did something wrong.
See ya next livestream. Can't wait :-)

Anyways have a good one, tomorrow it'll be snowing again!
