### ISSUE TITLE
Can't submit link in blender.today

### ISSUE THREAD

**Issue by ShadedRu** [armadillica/dillo#147]
When I click "Submit Link" button in Blender.Today page becomes bluish and nothing else happening. I've tryed it in Chrome (desktop and mobile), Firefox and Opera. In Chrome DevTools console there is an error: "Failed to load resource: the server responded with a status of 404 (NOT FOUND) /c/today/post/link?embed=1:1"

**Comment by venomgfx** [comment]
Is it possible that your user has negative karma? Can be seen on your profile.

**Comment by ShadedRu** [comment]
> Is it possible that your user has negative karma? Can be seen on your profile.
Yes, actually. And now I wonder - why i have negative carma? I don't think i broke any rules. Is there any way to improve carma?

**Comment by venomgfx** [comment]
You didn't break any rules. Unfortunately at the moment the karma system is attached to the voting system in general. So if you posted an idea in RightClickSelect that people disagree with (which is totally fine of course), your karma goes down. We are working to fix this in a completely new system where karma and votes are separate rankings. Karma should go down only if you get reported or flagged for breaking community rules.

**Comment by ShadedRu** [comment]
Thanks for your answers. :)
