### ISSUE TITLE
Wordpress site links can't get posted

### ISSUE THREAD

**Issue by 3dcinetv** [armadillica/dillo#148]
Hi. When I post the URL (or short URL) from [this Wordpress site](https://3dcinetv.com/blender-v-darker-ui-for-blender-to-showcase-your-work/): 
, this error appears:

![wpUrl](https://user-images.githubusercontent.com/11066585/107965344-6c613280-6f78-11eb-9a3a-4b5e627277de.jpg)

**Comment by fsiddi** [comment]
It looks like the website does not allow requests from Python (probably to prevent crawling) or any non-browser user.agent. The issue could be easily solved by changing the user-agent in the request, but this would probably go against the wishes of the 3dcinetv webmasters.

![Screenshot 2021-06-16 at 23 10 39](https://user-images.githubusercontent.com/451841/122294168-12f21b80-cef8-11eb-82c7-83514ac9e932.png)

In the latest version of the site, it's possible to post such link, but the title auto-fill functionality does not work.
