### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by brishbirali** [armadillica/dillo#149]
When trying to login with facebook it shows this message "Feature Unavailable: Facebook Login is currently unavailable for this app."

How do I fix it?

**Comment by venomgfx** [comment]
![image](https://user-images.githubusercontent.com/2890874/109849319-89bd1e80-7c51-11eb-9d23-f0c7a47cd999.png)

I can confirm the issue. 

For the time being I would suggest to not use Facebook login and use Blender ID instead. If you use the same email that you have for Facebook, on Blender ID, your user should match and you should have the same profile.

In the future Facebook login will be removed, so switching to using Blender ID is the best move to continue using Blender Community.

**Comment by JefferyWright** [comment]
Why is this still an option on the log in page if it doesn't work?

**Comment by fsiddi** [comment]
The issue has been fixed. Thanks for reporting it.
