### ISSUE TITLE
Twink accounts abuse issue?

### ISSUE THREAD

**Issue by IIIFGIII** [armadillica/dillo#150]
## Issue.
Recenlly, I had case when some [strange shit going on with my proposal](https://blender.community/c/rightclickselect/7shbbc/). Like I posted it, also shared with 6 people I know they are interested in Blender - so maybe vote it if thay want. Some of them even reply that they do it. It grow slowly as always, nothing speciall going on.... 

Then it loose votes rapidly in strange way. Like I wach it, refresh page time by time, then after another +/- 15 minutes I refresh and it drop from 8 vores to 2 ... after staying few hours with slow grow it just loose 6 votes in 15 minutes.  Some 6 prople gave -1 exatly in this 15 minutes? Without any word against proposal in comments.... Similar drop happened [to second popposal](https://blender.community/c/rightclickselect/6shbbc/) (I posted both in same time) but not so noticeable because people was vote it more. **Maybe I'm too suspicious but it looks for me like someone just sign in with N twinks and just give -1 from each.** 

I remember I saw such thing few month ago. Some new user (without lot of points) posted something about modifiers f I remember correct. It grow slowly to some +- 7 votes. Not the worst idea. Then it just drop to -2 or something. Same shit... I go to make cup of tea, go back to PC, refresh page and suggestion is dead. Same rapidly. Why? Who? Then it seemed to me that someone just "killed" this proposal.

I even commented this sugestion like "Guys why you gave so many -1?" and I remember user **-L0Lock-** reply me something like "Ahh, such things happen sometimes nowadays on RCS.". Sadly I can't check my comment history such far back days. If you guys have such functionality - you can check my comment history and find it.

Today it seems like I see same picture. [I proposed to improve loop select](https://blender.community/c/rightclickselect/Wthbbc/). Nothing too strange so anyone will have something against it so hard. Votes slowly grow. Some people comment it. I refresh it time by time, it has 22 votes...  BAM it loose 5 vote to 17... No argues in comments, no nothing. **I'm OK with fact that someone can give -1, but when it happened like this and in short time, it looks for me strange.** Also I strongly remember that proposal next to my "Hide childrens with parent" has much more votes, I may have false memory , but I remember it was far 10+ and it become 5... Correct me if I wrong.
![](https://i.imgur.com/c371BaR.png) 

## Get to the point
Maybe I really too suspicious, but it all strongly looks like some dude, no matter why, use twinks to kill proposals if he want.  

**Would be interesting to have some reply from you guys about what's going on (if you can check such things). Are my asumption correct about some same N users gave -1 to my last suggestions, and those same users do same activity to other prpoposals (there is reason to think that acounts used to kill suggestions). Or if I wrong and there is no signs of such activity this question will be solved.**

[I had proposed alternative, public voting system.](https://blender.community/c/rightclickselect/Yshbbc/) It look like people don't want to be too public, but we had lot of interesting discussion in comment section. Is it true about twinks or not, but I think we need some a bit more public voting system.

**Comment by fsiddi** [comment]
I looked into your post and could not see an obvious pattern of abuse. We have some ideas on how improve transparency of voting, and will implement them as the new version of version of blender community is released.

**Comment by IIIFGIII** [comment]
_I looked into your post and could not see an obvious pattern of abuse._ 

So you told me that you have looked at this and see no issues? Now with new RCS feature I can look as well. It just twinks that some crazy on Mario World and Tetris dude used to kill my topics (others too I guess)/upvotehis Mario World related topics or so. 7 accounts belong to single person, it's clear as sun in sunny day... Am I wrong in my conclusion? 
![](https://i.imgur.com/MwRi5b6.png)
![](https://i.imgur.com/Y8JgoHr.gif)


Here my second suggestion posted in same day. What we see here - same list of accounts, same list of this Mario something dude twinks. My suggestion was just killed 28 to 11 negative, 7 negative from this person 7 accounts. Then it worked in way - people see that suggestion is not popular > people think not to vote for this. Not because what I suggest is bad or wrong but because of such abuser someone. I was very disappointed of negative votes growing up on this suggestion because it is very sensative question for me.... Sadly to see now that I was right in suspicious.
![](https://i.imgur.com/YSDy3Lg.png)
![](https://i.imgur.com/FBxBwQe.png)

Same twinks was used for negative votes in my Advanced Loop Select suggestion I have mentioned here before... But you told me that you have checked and everything OK... are you gyus sure that everything is OK? Don't you guys want to remove those twink accounts and negative/positive votes generated by abusing them?
![](https://i.imgur.com/gEFd4gV.png)

**Comment by venomgfx** [comment]
Action was taken about this account. 

We can close this now and as reminder to add direct user report (at the moment it's possible to report posts/comments, but not users). In #152.
