### ISSUE TITLE
Blender ID login doesn't work properly

### ISSUE THREAD

**Issue by Harvester62** [armadillica/dillo#157]
Logging in with a Blender ID returns an Internal Server Error message. Strangely, it appears like the system recognized me, but I still get the Login link on the upper right corner of the screen, which in theory should be a Log Out option instead. In fact, I don't se a way to logout. Something still needs to be refined, but you're on the right track. Thanks you.

**Comment by fsiddi** [comment]
Should be fixed in ed563c0e936554d652ef2299c16c8b8ae8fe52bc - please follow up the the issue persists.
