### ISSUE TITLE
Bug: When adding "too big" resolution picture to comment.

### ISSUE THREAD

**Issue by IIIFGIII** [armadillica/dillo#160]
When adding too big resolution picture to comment then picture will be pasted in native resolution (while writing comment). This stretches text box and cause button "Comment" to run out of view. It still possible to press `Ctrl+Enter` to post comment. After posting comment picture shown as it have to in scaled resolutions.
![](https://i.imgur.com/zC5yhYu.png)
![](https://i.imgur.com/TQYUWpb.png)

**Comment by venomgfx** [comment]
Fixed! Thanks for the report.
