### ISSUE TITLE
Cannot edit posts on RCS

### ISSUE THREAD

**Issue by cmoleman** [armadillica/dillo#166]
Initially this was not a problem after the site redesign but since today I can no longer edit this (or any) post:

https://blender.community/c/rightclickselect/w0fbbc/

When I submit any edit: _"Internal Server Error. Oops we made a mistake somewhere. Try the frontpage instead."_

This error first occurred when I tried to edit the capitalization of a few words in the suggestion text, making no other changes... Perhaps this caused it? Either way, I've since also tried making other changes to the post and get the same error.

I now also get this error when trying to edit any other post. I have tried both Firefox and Chrome, same result.

**Comment by fsiddi** [comment]
The issue has been fixed. Thanks for the report!
