### ISSUE TITLE
Cannot scroll to see comments with Firefox 89.0.2

### ISSUE THREAD

**Issue by alexisb38** [armadillica/dillo#170]
Hello Pablo,

I was just checking out the new blender.community website and for some reason I cannot scroll down to see comments on long posts, I have no scroll bar on the right either (using firefox on windows).
I can scroll the list of posts, but not the posts themselves.
![image](https://user-images.githubusercontent.com/51906791/123979886-65840b00-d9c1-11eb-8ec4-c7249cabed56.png)

Apart from that great job on the new design, it looks much fresher.
I kinda miss the little thumbnails though, it takes longer to read than to look at an image at a glance

**Comment by venomgfx** [comment]
Hi, thanks for the report!

This bug was introduced this afternoon while attempting to fix something else on Safari. I've reverted it and should now work properly.
