### ISSUE TITLE
[Bug] Internal server Error when trying to upload on Graphicall

### ISSUE THREAD

**Issue by BlenderDefender** [armadillica/dillo#174]
When trying to upload a build on GraphicAll, an Internal Server Error message is displayed (https://blender.community/c/graphicall/create):
```
Internal Server Error

Oops, we made a mistake somewhere.

Try the front page instead.
```
This issue seems to exist for three weeks (at the time of this bug report), since the last upload on GraphicAll was three weeks ago.

Greetings,
Blender Defender

**Comment by fsiddi** [comment]
The issue has been fixed, thanks for reporting it! Let me know if you are able to upload a new build.
