### ISSUE TITLE
Creating a text post with no text gives an (unspecific) error

### ISSUE THREAD

**Issue by gregzaal** [armadillica/dillo#19]
![Screenshot](http://i.imgur.com/zUYF14G.png)

If the text submission has no actual text written, It gives an error. I think it would be fine to allow this, since someone may wish to create a post that is only an uploaded image (not a link to one).

**Comment by fsiddi** [comment]
Thanks for the feedback! We are going to look into it, possibly as a setting for each application. In the case of blender.today we even evaluated the possibility of creating galleries, so that would be a whole different post type.

**Comment by fsiddi** [comment]
This issue has been solved in the new release of Dillo.
