### ISSUE TITLE
Blender.Chat Hyperlinks with KaTeX.

### ISSUE THREAD

**Issue by blastframe** [armadillica/dillo#193]
Hello,
I am a Community Designer/Developer for Blender. Beneath the Blender Chat input message field is a link describing how to create a hyperlink in [\KaTeX\](https://katex.org/docs/supported.html#html).

From that link, it says links are created using this format:
`\href{https://katex.org/}{\KaTeX}`
This is incorrect in Blender Chat. Blender Chat uses this format:
`[KaTeX](https://katex.org/) `
This is very confusing for Blender Chat users.

My request is to somehow document this formatting in your application or create a hyperlink button that triggers a dialogue allowing the user to input the text & link separately. Thank you.

**Comment by fsiddi** [comment]
Hi, this looks like an issue with the blender.chat software itself. I'll look into this after updating to the next release.
