### ISSUE TITLE
My suggestion is not visible

### ISSUE THREAD

**Issue by xan2622** [armadillica/dillo#217]
Hi. 

tltr: I wrote a suggestion yesterday but after posting it I noticed that my post wasn't visible to others.
https://blender.community/c/rightclickselect/pk0p/

---

After posting it, my suggestion didn't appear in the list of suggestions on the left side, even after choosing the sorting option "New".

I shared the link of my suggestion to a few people but they couldn't access it.

When I noticed that my suggestion was not visible, (after posting it), I thought it could be due to my title that was quite long (maybe long titles make suggestions not appearing in the list on the left?) So I edited my title, making it shorter. But that didn't fix the issue.

Is there some delay between a post is submitted on the website and the moment it gets visible by other people?
Are suggestions reviewed by a moderator before they are actually seen online?

**Comment by venomgfx** [comment]
Hi,

Thanks for the report! It seems that for some reason your post got stuck in the "Processing" status. We'll look into it in case it happens in the future. I've fixed it now and published.

**Comment by xan2622** [comment]
Thank you very much

**Comment by xan2622** [comment]
Hi. 

This has happened again: 
https://blender.community/c/rightclickselect/j0ll/

Thanks in advance.

**Comment by venomgfx** [comment]
> This has happened again: https://blender.community/c/rightclickselect/j0ll/

Sorry about that. It should be published now.

**Comment by xan2622** [comment]
Thank you very much Pablo. 🤝
