### ISSUE TITLE
Link submission not working

### ISSUE THREAD

**Issue by gregzaal** [armadillica/dillo#22]
![2016-09-13_16-22-28_chrome](https://cloud.githubusercontent.com/assets/5604661/18477636/a2669cb6-79ce-11e6-901d-e00829cf1863.png)

Tried just pasting URL and letting it generate the title and image, doesn't work either. Maybe a URL with "?foo=bar" at the end is unsupported?

**Comment by fsiddi** [comment]
Thanks for reporting this! Will investigate ASAP.

**Comment by x-a-n-a-x** [comment]
I confirm this bug on https://rightclickselect.com/p/

**Comment by fsiddi** [comment]
This issue has been re-implemented in the latest version of Dillo and should work correctly now.
