### ISSUE TITLE
Screen overflow makes it impossible to post a comment

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#225]
On mobile, the text and even the buttons overflow the screen to the point of the buttons being outside of the screen with no possibility to even scroll horizontally to be able to click them:

![image](https://github.com/armadillica/dillo/assets/16049822/af5fe089-5249-4ebd-a73f-aec93d6d4290)

**Comment by L0Lock** [comment]
Update: not just on mobile:

![image](https://github.com/armadillica/dillo/assets/16049822/68efe160-046c-4bd8-8e10-fbb235d86c52)

**Comment by venomgfx** [comment]
Thanks for the report! Fixed in production. Separate note but also on mobile I hid the avatars now and reduced the padding to allow for more text to fit the screen.
