### ISSUE TITLE
On Houston when creating post with image

### ISSUE THREAD

**Issue by GottfriedHofmann** [armadillica/dillo#23]
I just tried to create a post on rightclickselect.com including and image, but got Houston all over. Then I submitted the same post without the image and was successful: https://rightclickselect.com/p/rendering/Xnbbbc/cycles-point-density-texture:-control-radius-by-attribute

The post was not created, so this issue seems to differ from issue #16 

The problematic image is this one (did select it from hard drive): http://pasteall.org/pic/show.php?id=107136

**Comment by fsiddi** [comment]
Issue should be fixed in the latest release of Dillo!
