### ISSUE TITLE
RCS posting with an animated GIF stuck on "processing"

### ISSUE THREAD

**Issue by jashear** [armadillica/dillo#234]
I created a Right-Click Select posting and decided to be cheeky by including an animated GIF. It seems that the posting is now permanently stuck in a "processing" state. It does not appear in the list of new postings, or on my profile page. And the problematic GIF can't be deleted.

Here's the URL:
https://blender.community/c/rightclickselect/0LxN/?sorting=hot#

The problematic attachment is 1.gif ( zYV5 ). It's not actually used in the post, but you can see it in the media list below. When I click the delete button and confirm that I want to delete it, nothing happens.

**Comment by venomgfx** [comment]
I've updated the post as published.
