### ISSUE TITLE
Developpers badges on RCS

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#239]
I'm not sure it's even a good idea, but just in case:

Following [this weird argument on RCS](https://blender.community/c/rightclickselect/g20j/?sorting=hot#comment-66425), I thought maybe there could be badges for developpers, contributors and addons devs on RCS?

I know we have at least the addon one on blenderartists,

And since we can use our blenderID to be on RCS, perhaps it can fetch our projects.blender.org info to know if we are any sort of contributor automatically?

**Comment by fsiddi** [comment]
Hi, improving the display of badges is on the roadmap. We are just tight on time currently, so it might take a while to get done. Thank you for bringing this up though!

**Comment by venomgfx** [comment]
Just to add to this, I've already made a `Blender Developer` badge that I add manually to developers I see on the comments. https://blender.community/c/rightclickselect/vZW0/?sorting=hot#comment-67429

Ideally it'd be done automatically from the commit rights in the Blender repository but unfortunately it's not the case yet.
