### ISSUE TITLE
Post does not appear

### ISSUE THREAD

**Issue by olyandros** [armadillica/dillo#244]
Hi!
I submitted a proposal on right click select (well, twice now) but it does not appear in the forum. If I click on "Submit Idea" it still tells me "Hi! It looks like you never posted here before. Please search the existing ideas and make sure you are not submitting a duplicate. "  Is it a bug?

**Comment by fsiddi** [comment]
Can you please share a screenshot of what you see?

**Comment by olyandros** [comment]
Here are some screenshots but I think there is nothing special to see.
I tired submitting on Linux and Windows with different browsers (FF and Vivaldi).

<img width="1279" alt="2023-10-10_18-13_1" src="https://github.com/armadillica/dillo/assets/64303559/2e7d914e-a814-4424-8b79-fdef47eb7a74">
<img width="1279" alt="2023-10-10_18-13" src="https://github.com/armadillica/dillo/assets/64303559/cb7a82e9-9afb-4882-a5f9-9b746c34d1f7">
<img width="1275" alt="2023-10-10_18-12_1" src="https://github.com/armadillica/dillo/assets/64303559/4b65e42b-6181-418c-bcba-6ab9a175d5d8">

**Comment by fsiddi** [comment]
Can you confirm that you are filling up the form and pressing the publish button?

**Comment by olyandros** [comment]
Here are my steps. I also noticed after I press publish it says review in the top right. Must the post be approved first or something?

<img width="1277" alt="2023-10-10_18-25_1" src="https://github.com/armadillica/dillo/assets/64303559/edc5d21d-ad02-4250-be4f-b8d3ad45bc11">
<img width="1279" alt="2023-10-10_18-26" src="https://github.com/armadillica/dillo/assets/64303559/54dcdf62-044e-4789-b9af-0de8620cd889">
<img width="1278" alt="2023-10-10_18-26_1" src="https://github.com/armadillica/dillo/assets/64303559/86e5341d-98d3-4fef-b5e0-b21d48358c0f">

**Comment by fsiddi** [comment]
Your post was waiting for approval indeed. Now it should be public and you should be able to post more.

**Comment by olyandros** [comment]
Okay, thanks. That should probably be communicated a bit more prominent ;-)

**Comment by L0Lock** [comment]
Now [this same post](https://blender.community/c/rightclickselect/G95y/#) is stuck at the top of the posts list when sorted by newest:

![image](https://github.com/armadillica/dillo/assets/16049822/7396ffba-f624-4734-b678-9c3e2bb3c840)

**Comment by venomgfx** [comment]
> IDK if it's related, but now [this same post](https://blender.community/c/rightclickselect/G95y/#) is stuck at the top of the posts list when sorted by newest

Strange, that post had the status "published" but didn't have a published date at all. I've added one now so should behave normally. Thanks!
