### ISSUE TITLE
Missing Outliner category on RCS

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#247]
I think we are supposed to have categories for all the editors? If so, we missed the outliner:

![image](https://github.com/armadillica/dillo/assets/16049822/c3a3640b-94fa-4908-86ae-3c97cda1f4a8)

**Comment by venomgfx** [comment]
I don't think we should have every editor as category, better to have categories around workflows or specific features (Library Overrides is not an editor, but a feature).

That being said, the Outliner is its own thing so it deserves a category. Just created it.

Thanks!
