### ISSUE TITLE
Development url not supported

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#252]
I'm trying to change the development status of [Better visual feedback for Autokey ⁠— Right-Click Select](https://blender.community/c/rightclickselect/qxcbbc/?sorting=hot), using this link:

https://projects.blender.org/blender/blender/pulls/105574

But....

![image](https://github.com/armadillica/dillo/assets/16049822/2e36c23b-a078-477b-86a5-23b45b5afd26)

**Comment by venomgfx** [comment]
Fixed in production. Thanks!

![image](https://github.com/armadillica/dillo/assets/2890874/338de592-7166-409e-9d2a-d143adb54a0a)
