### ISSUE TITLE
Right-Click Select filled with Spam

### ISSUE THREAD

**Issue by blastframe** [armadillica/dillo#253]
Hello, [Right-Click Select](https://blender.community/c/rightclickselect/) has been filled with spam posts:
![Screenshot 2024-01-06 at 11 18 03 AM](https://github.com/armadillica/dillo/assets/3729547/16c71b0b-aeda-4c04-87fe-ab747e39e9e9)

**Comment by fsiddi** [comment]
Did a cleanup pass, thank you!
