### ISSUE TITLE
Blender Community being discontinued - what does it mean for dillo?

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#254]
I just saw the announcement on blender.community. I'm not sure where else to post that, so here I go, sorry if it isn't the appropriate place.

<details><summary>(Quote)</summary>

### Is Blender Community being discontinued?

Yes. All communities except Right-Click Select will be shut down.

Blender Community started back in 2014 as a side project for fun to work in the evenings and weekends, with the mission to give the community a place to share news and connect. Later on it grew into adopting an ideas board (Right-Click Select) and Blender builds (GraphicAll). Over the years Blender's buildbot took over the distribution of builds, and social media and forums took over BlenderToday. So we have decided to shut down Blender Community, and focus on the side of it that the community really wants to see grow: Right-Click Select.

Over the coming months of 2024 we want to build a new platform from scratch, that takes over and expands the concept of Right-Click Select. Fully open source as part of the Blender project, to which anyone can contribute and help curate and moderate.

Language/region specific Blender communities can be found on the ever-growing list at [blender.org/community](https://www.blender.org/community/)

Making Blender Community has been an amazing experience. A journey of learning and discovering what works and what doesn't. There is a clear need for a space to share and discuss ideas and we can't wait to build this together.

</details>

I wonder the ramifications of this:

- Will the new platform be a new version of dillo, or something completely different?
    - If different: will dillo continue to exist and is our participation here still relevant?
    - If still dillo, should the community wait till its release to the public, or will the community be involved in it, and are the current tickets still relevant for that?
- Will there be a proper announcement of all of this on code.blender.org and/or Blender's Youtube channel?

**Comment by fsiddi** [comment]
I can confirm that:
* the platform will be free/open source software, probably built from scratch
* decision on how this is designed/implemented will be communicated publicly

Until then, everything keeps working as of now.
