### ISSUE TITLE
Badges induce false affiliations

### ISSUE THREAD

**Issue by Lauloque** [armadillica/dillo#255]
Not sure if this should be reported on Dillo since the badges aren't unique to that platform, but on the other hand it seems that the badges are different on RCS/BlenderCommunity, and it's on RCS that I have issues with them. Let me know if I should report this elsewhere.

The scenario is quite simply that I somewhat frequently see people being addressed as though they are Blender developers or somewhat related to the BF, or having some form of decision-making authority.

And I suspect part of the reason why these affiliations are made, is this:

![image](https://github.com/user-attachments/assets/36a0bfca-98ce-4b3a-8057-3f32215bd241)

![image](https://github.com/user-attachments/assets/ff70ada3-a76b-451d-89f0-924867c5018b)

![image](https://github.com/user-attachments/assets/29d76736-4054-44df-88c1-5e0f25eb6c78)

![image](https://github.com/user-attachments/assets/389079f5-eeea-4cbb-b3ef-8bff79b196df)

Only two of these badges are actual signs of a form of authority. All the others are just shiny collectibles.  
And I think mixing the two with no clear distinction is quite an issue.

And it's just an unpleasant situation for everyone. Because on one hand, it makes it indeed possible for ill-intentioned users to impersonate authority. And on the other hand, it also leads to unwanted confusions, like people on RCS assuming you are a dev taking decisions on their proposals, or having informations or duties that you don't have, or thinking that you are impersonating authority.

If you take the perspective of anyone unfamiliar with all those badges: what prevents them from assuming "Blender Studio" or "open movie" badges = Someone working for Blender? 

The quick'n'dirty solution could be to just rename all those collectibles badges so something descriptive of what they are. Take example from the Development Fund ones:

![image](https://github.com/user-attachments/assets/01701224-9282-4678-a80d-b9f02e528a5f)

Just the fact that it states "supporter" already makes this clearer.

So we could also have open movies supporters. 

For the Blender Studio ones, it seems the Blender Studio page is already better in that regard, so RCS/BC could just use the same name:

![image](https://github.com/user-attachments/assets/b1de13c9-1d75-45c9-a9c9-b65363bf736d)

**Comment by venomgfx** [comment]
Good point, it is indeed prone to be confused with endorsement from Blender.

I've updated all the missing badges now to include the word `supporter`.

Thanks!

**Comment by Lauloque** [comment]
Well that was fast :D Thanks!
