### ISSUE TITLE
/logout doesn't logs you out

### ISSUE THREAD

**Issue by venomgfx** [armadillica/dillo#37]
https://blender.community/logout seems to lead back to /c/ and not logging out.

Only workaround is deleting the cookie _remember_token_ from Developer Tools. Tested using Blender ID.

**Comment by venomgfx** [comment]
This seems to work fine locally now. The *remember_token* cookie gets deleted on log out. IIRC it was fixed, just not in production yet, right @fsiddi ?

**Comment by fsiddi** [comment]
Fixed in the latest deploy (depended on a Pillar update).
