### ISSUE TITLE
Links with https not recognized by Dillo

### ISSUE THREAD

**Issue by bkurdali** [armadillica/dillo#4]
Hi all, recently updated urchn.org to use ssl via letsencrypt. when typing the url into dillo using https:// instead of http:// the submit button stays greyed out and the link is not recognized. Removing the s and submitting  works again.

**Comment by venomgfx** [comment]
Ah yes, I've noticed this in other cases. Will look into it next week. Thanks!

**Comment by fsiddi** [comment]
I have tested this again with an https site with letsencrypt and ti works. Feel free to open again if the issue reappears!
