### ISSUE TITLE
[Feature request] Follow people

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#45]
Read my mockup [here](https://blender.community/c/rightclickselect/wzbbbc/follow-people-on-blender-community)

**Comment by ChameleonScales** [comment]
However, this will certainly lead to an increasing posting rate, as some people may want to share everything they do to their followers. The question is : do you want this and can the server handle it ?

**Comment by ChameleonScales** [comment]
Actually, the more I think of it, the less I'm fond of the idea. I fear turning this website into a social network would require a huge amount of work to eventually resemble already existing tools and I also fear it will lead some people to post more and more often to talk about less and less important things and the timeline will progressively lose interest. Maybe we should leave such social network tools to social networks and there are some very good ones in the FOSS world.

**Comment by xan2622** [comment]
I like the idea (to be able to follow people).
It might be interesting to follow someone, especially if he/she already posted and liked interesting ideas. It would help find other interesting ideas published on RCS.

**Comment by venomgfx** [comment]
This is already implemented in the upcoming version 4.0, under development and to be released later this year.

**Comment by ChameleonScales** [comment]
Awesome! Also I backtrack on what I said. The website has become a lot more popular so being able to filter what you see by the accounts you're more interested in makes more sense now.
