### ISSUE TITLE
Some old posts show html code

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#47]
Some old posts I made (but not all of them) show all the html code instead of images, text layout and text fomatting.
For example [this one](https://blender.community/c/rightclickselect/Crbbbc/tablet-pressure-:-minimum-radius) works fine and [this one](https://blender.community/c/rightclickselect/hsbbbc/find-ideas-i-ve-voted-or-commented) doesn't.

I tried editing the post and while I was doing so, the preview showed the image and the layout but after I saved and refreshed it returned to displaying the code.
Note that the concerned post is originally written in markdown.

**Comment by venomgfx** [comment]
Related to #43

**Comment by fsiddi** [comment]
The issue has been fixed and will be deployed soon.

**Comment by ChameleonScales** [comment]
you guys get the stuff done
