### ISSUE TITLE
URLs of posts opened from profile page are 404

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#49]
How to reproduce :

- open anyone's profile page (including yours)
- click on any post on the left side
- refresh the page (or copy the URL and paste it on another tab) : the page is 404

**Comment by dfelinto** [comment]
Confirmed. The issue is that in user.pug we do:
`| {% set post_url = url_for('posts.view', community_url=project.url, post_shortcode=post.properties.shortcode) %}`

And project is the same for all of them. Instead, in users/routes.py, we need to aggregate the post project in the posts array.

**Comment by ChameleonScales** [comment]
Thank you ! it works smoothly now.
