### ISSUE TITLE
Support html formatting again

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#51]
All the old posts and comments containing html formatting such as `<kbd>` display as html code now.
Supporting it again would be great

**Comment by venomgfx** [comment]
Can you link to a post having such issue please? Thanks!

**Comment by ChameleonScales** [comment]
Hey, you implemented it ! (at least the <kbd> formatting). Thank you !

**Comment by venomgfx** [comment]
Yes! Some weeks/months ago. Forgot to close the issue. Thanks for reporting!

**Comment by L0Lock** [comment]
Hi! Allow myself to refresh this topic. The new Dillo is live, it looks awesome! Though the <kbd> support seems to be lost:

![image](https://user-images.githubusercontent.com/16049822/122364692-42397480-cf5a-11eb-8f1a-2fa565f63dec.png)

**Comment by ChameleonScales** [comment]
@venomgfx Looks like this issue is back
