### ISSUE TITLE
Can't delete my own post

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#56]
When clicking on Delete next to Cancel and Save changes, I get this error :
```
Couldn't delete. This shouldn't happen, please report it
FORBIDDEN
```

Here are the posts I'm trying to delete
https://blender.community/c/rightclickselect/Bkbbbc/
https://blender.community/c/rightclickselect/Xjbbbc/

**Comment by venomgfx** [comment]
Is this issue still happening?

**Comment by venomgfx** [comment]
Could you try again? Sorry to bother, we went through community permissions recently.

**Comment by ChameleonScales** [comment]
Still happening

**Comment by venomgfx** [comment]
Could you please try again? It's Dillo 4.0 now! :D

**Comment by ChameleonScales** [comment]
Yep, it works now! Thank you!
