### ISSUE TITLE
Night mode does not work

### ISSUE THREAD

**Issue by Martincho84** [armadillica/dillo#57]
In both firefox and chrome, night mode does not work. I've cleared cache of navigation, cokkies, etc. but I can not make it work. 

Sometimes the web is "recharged" and it is without CSS styles. (image attached).

![screenshot_20180111_112015](https://user-images.githubusercontent.com/35337938/34830089-978ff2f8-f6c1-11e7-9b33-1a36a2392672.png)

**Comment by venomgfx** [comment]
Confirmed. Will investigate as soon as possible.

Thanks for the report.
