### ISSUE TITLE
Date creation should be the one when the post was published

### ISSUE THREAD

**Issue by venomgfx** [armadillica/dillo#58]
It takes time to write an article, so sometimes when we publish it already says "20 minutes ago" when it was actually just published.

Setting current time as the _created time when publishing would make sense.

**Comment by sybrenstuvel** [comment]
I would rather add an extra field like `published_timestamp` or `published_datetime`. That way you don't change the semantics of `_created`.

**Comment by venomgfx** [comment]
Good point! That way we have _created, _updated, and published.

**Comment by venomgfx** [comment]
Fixed in Dillo 4.0
