### ISSUE TITLE
To comment, an account in Blender Cloud is required

### ISSUE THREAD

**Issue by Martincho84** [armadillica/dillo#60]
It is possible to make publications, but if I want to comment on any publication, it asks me to have an account in Blender Cloud. It succeeds in all communities within Blender Comunity.

I subscribed to Spanish-speaking "Blender Hoy".
![screenshot_2](https://user-images.githubusercontent.com/35337938/35126423-21ded724-fc8c-11e7-867b-dbaa3bd87d73.jpg)

**Comment by venomgfx** [comment]
You don't need an account on Blender Cloud, the message is wrong. Thanks for the report we are investigating it and it is the highest priority to fix it.

One thing fixed, one thing breaks :cry:

**Comment by ChameleonScales** [comment]
is it only since today ? because I can't add comments anymore.

**Comment by Martincho84** [comment]
I understand that since an update was made in the Blender Comunity system. About a day ago.

**Comment by venomgfx** [comment]
Yes it seems to have been introduced in the last update a day ago. We have found the issue and we are working on it right now. We will try to deploy tonight or tomorrow. Wish us luck!

**Comment by venomgfx** [comment]
Could you check now? Thanks!

**Comment by Martincho84** [comment]
The problem in my case was solved! What speed this team has!

**Comment by venomgfx** [comment]
Credits go to the one and only @fsiddi for fixing it even though it's Friday night! :balloon:

**Comment by Martincho84** [comment]
A good Friday party is well deserved!

**Comment by ChameleonScales** [comment]
Works for me as well. Thanks !
