### ISSUE TITLE
Can't access my profile anymore

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#62]
I can access other people's profiles but not mine. I get a 500 error message.
```
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

**Comment by venomgfx** [comment]
Confirmed.

For some reason other channels work except yours, we are investigating the issue (@fsiddi maybe it has something to do with the deletion of a post recently and activities looking for comments there or so?)

**Comment by ChameleonScales** [comment]
the bug seems to be gone. Have you done something ?

**Comment by fsiddi** [comment]
Hi,

Yes I did a temporary workaround for the issue, which still needs to be fully investigated and solved. Will report more about it here later.

**Comment by ChameleonScales** [comment]
Now same for moleman :
https://blender.community/u/c_moleman

**Comment by fsiddi** [comment]
The issue was related with undeleted posts/notifications and should have been solved time ago. Feel free to reopen if the problem appears again.
