### ISSUE TITLE
code formatting appearance

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#68]
The ``` box code formatting has an unusual appearance : it shows both an inline background and a box background :
![](https://i.imgur.com/4TWS3NO.png)

Let me equalize the image to make that more visible :
![](https://i.imgur.com/rcuBrWn.png)

I'm not sure this is so useful.

Also I find this blue a little too bright personally

**Comment by venomgfx** [comment]
Fixed in Pillar and will be part of the next deploy.

Thanks for the report!
