### ISSUE TITLE
Error 500 when try to create new post 

### ISSUE THREAD

**Issue by py354** [armadillica/dillo#70]
When i create new post i get error 500 with this message in console:
`pillarsdk.exceptions.BadRequest: Failed. Response status: 400. Error message: b'{"_status": "ERR", "_error": {"code": 400, "message": "An exception occurred: \'NoneType\' object has no attribute \'save_object\'"}}'
`

**Comment by fsiddi** [comment]
Hi! Could you please provide some more info on how you set up the project? I just checked the readme and it does not look very complete, so maybe we are missing some step there.

**Comment by fsiddi** [comment]
Ok, i definitely need to spend some time trying to reproduce this myself. How are you logging in?

**Comment by py354** [comment]
I use google oauth (there's no errors)

**Comment by py354** [comment]
Sorry, it was missclick. Now i get 422 error:
`pillarsdk.exceptions.ResourceInvalid: Failed. Response status: 422. Error message: b'{"_status": "ERR", "_error": {"code": 422, "message": "The request was well-formed but was unable to be followed due to semantic errors."}}'
`

**Comment by venomgfx** [comment]
Is this still an issue?

**Comment by venomgfx** [comment]
Closing until we can replicate.
