### ISSUE TITLE
A "closed" tag for granted requests and a "exclusion" system for tags filtering

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#73]
As I posted [on RCS](https://blender.community/c/rightclickselect/mJbbbc/) and get some nice answers, I post that here too.

RCS Is open for a long time now, some requests are here for years, and some of them have been granted already.

The result is that some topics here are irrelevant when we search requests to react on and vote in.

E.G. :

- [Unlimited Layers and Layer Manager](https://blender.community/c/rightclickselect/Kbbbbc/unlimited-layers-and-layer-manager) → solved by collections ?
- [Cycles Shadow Catcher material](https://blender.community/c/rightclickselect/Sbbbbc/cycles-shadow-catcher-material) → we have shadow catcher option now
- [UDIM / UV Tiles Support](https://blender.community/c/rightclickselect/ybbbbc/udim-uv-tiles-support) → coming for 2.8

My proposal consist of two points :

1. add a new "closed" tag, that admins can assign to any request considered as granted
2. add a "exclude" option in the tags filtering, that way we can both "constrain" search result on a particular tag as well as exclude topics with a particular tag.

By the way, maybe this can be pushed even further:

- we can have more than just a "closed" tag, why not have "released", "in dev", "planned", "rejected", ... so that we also have a clear simple yet efficient dialogue with the main dev team ?
- such "dev status" tags could be visually highlighted

A nice example IMHO is [Allegoritmic's Feedback site](https://allegorithmic.uservoice.com/forums/261284-substance-painter):
![](https://i.imgur.com/ElclGyX.png)

I think something like this would be the top of the "nice to have" features. But at least the two first basic request could be "must have first".

**Comment by fsiddi** [comment]
Thanks for the suggestion, we are aware of the need for a status tagging system and it's almost on top of the list for features to be implemented as soon as development for Dillo resumes.

**Comment by fsiddi** [comment]
Implemented and deployed!
