### ISSUE TITLE
Display post's title in notifications & profile's history

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#87]
It may be a subjective feeling, but:
Right now, its difficult to track what's happening on RCS.

![demo pic](https://user-images.githubusercontent.com/16049822/49157381-f4b77680-f31f-11e8-93f5-549abb7617c4.png)

Right now, the notification system only says to whom it has been answered. As a single person can send multiple things on a single post, and we read only one post at a time, I think it makes more sense to display the post title where the answer is sent.

That way, you can read any new answer of one post and clear all the notifications for that post. Without that, you just click on notifications and get redirected to the same topic again and again.

For the profile page, it's just that it's more useful to have more information than "I commented".

**Comment by fsiddi** [comment]
Closing in favor of #108.
