### ISSUE TITLE
[Feature request] "Accept as solution" (mostly for RCS)

### ISSUE THREAD

**Issue by ChameleonScales** [armadillica/dillo#88]
Similarly to what we have in Discourse, a feature that can be enabled or disabled for each community (since blender.today and others don't need it), allowing the OP or an admin to accept a comment as a solution.
The effect of pressing that button would be to update the custom property of the dillo post to "Done" and leave a notification to all commenters and mostly upvoters (although to keep consistency, the same notification should be sent if the OP changes the custom property by editing the post).

I actually made an RCS proposal for it a while ago:
https://blender.community/c/rightclickselect/60bbbc/

**Comment by L0Lock** [comment]
Not sure "accept as solution" is the right way to work.
There isn't really a form of acceptance in RCS.
And if the devs "accept" it or "reject it", it might have several steps/states behind those simple words:

It can be fully rejected, or soft rejected (like "not now" or "need more info"), accepted but way down in the to-do list or currently in developpment, or "done".

That's what the "Status Dev" are made for:

![demo pic](https://i.imgur.com/Owx3mvX.png)

I guess the notification idea might be interesting though.

**Comment by ChameleonScales** [comment]
Yeah I don't think it makes sense anymore. As far as I'm concerned this issue can be closed.
