### ISSUE TITLE
[bug] Replies sorting seems broken

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#93]
I first thought it was simply inverted, the most recent on top and so on:

![opera_2018-12-28_12-05-18](https://user-images.githubusercontent.com/16049822/50513569-dec0e100-0a98-11e9-9b1b-3efc6546eabe.png)

(_Which in my personal taste isn't nice and intuitive, as it brokes the reading flow. If it's intended, could this be optional so everyone chooses it's favorite sorting ?_)

BUT! Then I started to notice some things like here:

![2018-12-28_11-59-51](https://user-images.githubusercontent.com/16049822/50513461-432f7080-0a98-11e9-8e08-77de26608694.png)

If you look at the time marks, it indicates that "visprotis" replied to his own comment about five hours **before** the comment was posted.  
Or maybe it's a bug with the 24h format display?

Dunno what's going on.  
Thanks for your attention.

**Comment by venomgfx** [comment]
Thanks for the report! We'll look into it.

Bit more context, there was a recent change in comments so they're sorted by most liked, this should only be applied to top-level comments though, not replies. This might be causing the issue.

**Comment by venomgfx** [comment]
Just a follow-up. Since this bug is not really on Dillo but on the framework we use, I've [reported the issue there](https://developer.blender.org/T62049).

**Comment by venomgfx** [comment]
It's been fixed and is now live in production!
