### ISSUE TITLE
[bug] can't edit anything due to error "Failed to submit comment"

### ISSUE THREAD

**Issue by L0Lock** [armadillica/dillo#94]
It's been two days now that I get this error when trying to submit an edit on a comment:

![image](https://user-images.githubusercontent.com/16049822/52858436-6a1a3280-312a-11e9-9d2b-ba98992302b2.png)

Tried with different browsers (Opera, Google Chrome, Firefox), at differnet time and on different topics.

**Comment by fsiddi** [comment]
The issue should have been solved now! Please try again and feel free to reopen the issue it the problem persist.
