### ISSUE TITLE
Post Components in New Listing

### ISSUE THREAD

**Issue by venomgfx** [armadillica/dillo#96]
Components currently missing in the 'post' object of the new listing in Dillo.

* **Project**
  Name, URL.
* **Comments count**
  Number, since it's just for display.
* **Custom properties (Status Dev)**
  Label, Slug. That way we could format so we have a `status-dev_{status}` class added e.g. RCS 'done' proposals.

**Comment by fsiddi** [comment]
* **Project**
Available with `post.project.name` and `post.project.url`
* **Custom properties (Status Dev)**
Available with: `{% if post.properties.status_dev %}status-dev_{{ post.properties.status_dev }}{%endif %}`
* **Comments count**
This requires a bit of thinking

**Comment by fsiddi** [comment]
Comments count has been added, and is available in `post.properties.comments_count`.
