### ISSUE TITLE
User profile to use posts_lists

### ISSUE THREAD

**Issue by venomgfx** [armadillica/dillo#97]

**Comment by venomgfx** [comment]
Fixed the basic layout by simply copypasting from posts_list, but maybe it should just re-use that.

It's still missing the "Load More Posts", need to check with @fsiddi about that.

**Comment by venomgfx** [comment]
[Fixed again](ffede8b), we should really just re-use the posts_list.html template.

Will leave the bug open until we do so (since it's still broken in the sense it lacks all listing features)

**Comment by IIIFGIII** [comment]
Emm - "I can't see all of my own suggestion on my profile page." is closed but it still work same. Closed mean "fixed" of something else?

**Comment by fsiddi** [comment]
The issue you reported was connected with this one. Once this is issue is closed, your issue will be solved.

**Comment by venomgfx** [comment]
Dillo 4.0 fixes this.
